# Generated by Django 5.2.1 on 2025-06-06 16:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_kelamin', models.CharField(max_length=1)),
                ('kehamilan', models.FloatField()),
                ('glukosa', models.FloatField()),
                ('tekanan', models.FloatField()),
                ('kulit', models.FloatField()),
                ('insulin', models.FloatField()),
                ('berat', models.FloatField()),
                ('tinggi', models.FloatField()),
                ('bmi', models.FloatField()),
                ('riwayat', models.FloatField()),
                ('usia', models.FloatField()),
                ('hasil_persen', models.FloatField()),
                ('hasil_risiko', models.FloatField()),
                ('hasil_tipe', models.CharField(max_length=255)),
                ('hasil_saran', models.TextField()),
                ('tanggal_input', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
